import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/navbar/Navbar";
import Footer from "@/Components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="top-0 w-full h-full overflow-hidden">
        <Navbar />
        <div className="min-h-screen mt-16">
        {children}
        </div>
        
        <Footer /> 

        </div>
       
      </body>
    </html>
  );
}
